server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: demo

people:
  enabled: true
  name: 小花
  gender: 女

